CustomerInvoicesWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CustomerInvoicesWeb.Controllers
{
    /// <summary>
    /// Controlador Home
    /// </summary>
    public class HomeController : Controller
    {
        /// <summary>
        /// Método Index, método encargado de mostrar la pantalla principal
        /// </summary>
        /// <returns>Regresa una vista</returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

CustomerInvoicesWeb/Controllers/SearchController.cs
using CustomerInvoicesLogic;
using CustomerInvoicesModels.Request;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace CustomerInvoicesWeb.Controllers
{
    /// <summary>
    /// Controlador de búsqueda, encargado de realizar las búsquedas dependiendo del algoritmo que se ejecute
    /// </summary>
    public class SearchController : Controller
    {
        /// <summary>
        /// Método de búsqueda por día
        /// </summary>
        /// <param name="customerId">Id del usuario</param>
        /// <param name="startDate">Fecha de inicio</param>
        /// <param name="endDate">Fecha de fin</param>
        /// <returns>Objeto del tipo Json</returns>
        public JsonResult normalSearch(string customerId, string startDate, string endDate)
        {
            var sDate = DateTime.MinValue;
            var eDate = DateTime.MinValue;

            if (DateTime.TryParse(startDate, out sDate) && DateTime.TryParse(endDate, out eDate))
            {
                var request = new InvoiceCountRequest(customerId, sDate, eDate);
                var result = new PerDayLogic().GetCustomerInvoicesCount(request);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return Json(new { message = "Error" }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Método de búsqueda por divición a la mitad
        /// </summary>
        /// <param name="customerId">Id del usuario</param>
        /// <param name="startDate">Fecha de inicio</param>
        /// <param name="endDate">Fecha de fin</param>
        /// <returns>Objeto del tipo Json</returns>
        public JsonResult halfSearch(string customerId, string startDate, string endDate)
        {
            var sDate = DateTime.MinValue;
            var eDate = DateTime.MinValue;

            if (DateTime.TryParse(startDate, out sDate) && DateTime.TryParse(endDate, out eDate))
            {
                var request = new InvoiceCountRequest(customerId, sDate, eDate);
                var result = new HalfLogic().GetCustomerInvoicesCount(request);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return Json(new { message = "Error" }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Método de búsqueda por divición rándom
        /// </summary>
        /// <param name="customerId">Id del usuario</param>
        /// <param name="startDate">Fecha de inicio</param>
        /// <param name="endDate">Fecha de fin</param>
        /// <returns>Objeto del tipo Json</returns>
        public JsonResult randomSearch(string customerId, string startDate, string endDate)
        {
            var sDate = DateTime.MinValue;
            var eDate = DateTime.MinValue;

            if (DateTime.TryParse(startDate, out sDate) && DateTime.TryParse(endDate, out eDate))
            {
                var request = new InvoiceCountRequest(customerId, sDate, eDate);
                var result = new RandomLogic().GetCustomerInvoicesCount(request);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return Json(new { message = "Error" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

CustomerInvoicesWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<link href="~/Content/main.css" rel="stylesheet" />

<div class="jumbotron row">
    <h2>Ejercicio resuelve</h2>
    <div class="col-md-6">
        <form id="dataToValidate">
            <p>Id del cliente <input name="customerId" id="customerId" type="text" required /></p>
            <p>Fecha de inicio <input class="datepicker" name="startDate" id="startDate" type="text" required /></p>
            <p>Fecha de fin <input class="datepicker" name="endDate" id="endDate" type="text" required /></p>
            <input id="submitButton" type="submit" hidden/>
        </form>
    </div>
    <div class="col-md-6">
        <p>Número de facturas <input name="customerInvoices" id="customerInvoices" type="text" /></p>
        <p>Número de llamadas <input name="totalCalls" id="totalCalls" type="text" /></p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Búsqueda sin optimizar</h2>
        <p>Este algoritmo ejecuta una llamada por cada día en el rango de fechas</p>
        <p><a class="btn btn-default" id="normalSearch" href="#">Buscar &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Algoritmo 1</h2>
        <p>Este algoritmo divide de forma recursiva a la mitad el rango de fechas mayores de 100 facturas</p>
        <p><a class="btn btn-default" id="halfSearch" href="#">Buscar &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Algoritmo 2</h2>
        <p>Este algoritmo divide de forma recursiva en rangos aleatorios si el rango de fechas rebasa las 100 facturas</p>
        <p><a class="btn btn-default" id="randomSearch" href="#">Buscar &raquo;</a></p>
    </div>
</div>

<div id="loader-wrapper" hidden>
    <div id="loader"></div>
</div>

@section scripts
{
    <script type="text/javascript">
        $('.datepicker').datepicker({
            dateFormat: 'yy-mm-dd',
            defaultDate: '2017-01-01'
        });

        $('#normalSearch').click(function (e) {
            sendRequest('@Url.Action("normalSearch", "Search")')
        })

        $('#halfSearch').click(function (e) {
            sendRequest('@Url.Action("halfSearch", "Search")')
        })

        $('#randomSearch').click(function (e) {
            sendRequest('@Url.Action("randomSearch", "Search")')
        })

        function sendRequest(url) {
            var customerId = $('#customerId').val();
            var startDate = $('#startDate').val();
            var endDate = $('#endDate').val();

            if (!$('#dataToValidate')[0].checkValidity()) {
                $('#submitButton').click();
            }
            else {
                $.ajax({
                    url: url,
                    type: 'GET',
                    data: { customerId: customerId, startDate: startDate, endDate: endDate },
                    contentType: 'application/json; charset=utf-8',
                    beforeSend: function () {
                        $('#loader-wrapper').show();
                    },
                    success: function (response) {
                        $('#customerInvoices').val(response.CustomerInvoices);
                        $('#totalCalls').val(response.Calls);
                    },
                    error: function () {
                        alert("Algún parámetro proporcionado es incorrecto");
                    },
                    complete: function () {
                        $('#loader-wrapper').hide();
                    }
                });
            }
        }
    </script>
}

CustomerInvoicesWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ejercicio resuelve", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - José Jair Guillén García</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)
</body>
</html>